/**
 * Readonly list of supported date/time format strings. Use with `outputFormat` in {@link genRecurDateBasedList} or as the second argument to {@link formatDate}; compatible with `localeString.lang`, not with `localeString.formatOptions`.
 *
 * Includes: ISO (e.g. YYYY-MM-DD, YYYY-MM, YYYY-MM-DD HH:MM); US slash and dash (MM/DD/YYYY, MM-DD-YYYY, with time); European dot and dash (DD.MM.YYYY, DD-MM-YYYY, with time); month-year only (MMMM YYYY, MMM YYYY); RFC-style (DD MMM YYYY HH:MM:SS); weekday + date/time (EEE, DD MMM YYYY HH:MM:SS); time-only (HH:MM, HH:MM:SS, with A or Z); and compact (YYYYMMDD).
 *
 * Token meanings (all uppercase): YYYY = 4-digit year, YY = 2-digit year; MM = month 2-digit, M = month no zero; DD = day 2-digit, D = day no zero; HH = hour (12h if format contains ` A`, else 24h); MM after colon = minutes; SS = seconds, SSS = milliseconds; A = AM/PM; EEE = weekday short (locale), EEEE = weekday long; MMM = month short (locale), MMMM = month long; DDD = day of year (3-digit); Z = timezone offset (+HH:mm).
 *
 * @constant
 */
export const OUTPUT_FORMATS = [
  'MM/DD/YYYY',
  'MM/D/YYYY',
  'M/DD/YYYY',
  'M/D/YYYY',
  'DD/MM/YYYY',
  'D/MM/YYYY',
  'DD/M/YYYY',
  'D/M/YYYY',
  'YYYY-MM-DD',
  'YYYY-MM-D',
  'YYYY-MM',
  'DD-MM-YYYY',
  'D-MM-YYYY',
  'MM-DD-YYYY',
  'M-DD-YYYY',
  'MM-D-YYYY',
  'M-D-YYYY',
  'YYYY/MM/DD',
  'YYYY/MM/D',
  'MMM DD, YYYY',
  'MMM D, YYYY',
  'MMMM DD, YYYY',
  'MMMM D, YYYY',
  'MMMM YYYY',
  'MMM YYYY',
  'EEEE, MMMM DD, YYYY',
  'EEEE, MMMM D, YYYY',
  'EEEE, DD MMM YYYY',
  'EEEE, D MMM YYYY',
  'DD MMM YYYY',
  'D MMM YYYY',
  'DD MMMM YYYY',
  'D MMMM YYYY',
  'DD MMM YYYY HH:MM:SS',
  'D MMM YYYY HH:MM:SS',
  'EEE, DD MMM YYYY HH:MM:SS',
  'EEE, D MMM YYYY HH:MM:SS',
  'EEE, DD MMM YYYY HH:MM:SS A',
  'EEE, D MMM YYYY HH:MM:SS A',
  'EEE, DD MMM YYYY HH:MM',
  'EEE, D MMM YYYY HH:MM',
  'EEE, DD MMM YYYY HH:MM:SS.SSS',
  'EEE, D MMM YYYY HH:MM:SS.SSS',
  'EEE, DD MMM YYYY HH:MM:SS.SSS A',
  'EEE, D MMM YYYY HH:MM:SS.SSS A',
  'YY/MM/DD',
  'YY/MM/D',
  'YY-MM-DD',
  'YY-MM-D',
  'YYYYMMDD',
  'YYYYDDD',
  'DD.MM.YYYY',
  'D.MM.YYYY',
  'DD.MM.YY',
  'D.MM.YY',
  'DD.MM.YYYY HH:MM',
  'D.MM.YYYY HH:MM',
  'DD.MM.YYYY HH:MM:SS',
  'D.MM.YYYY HH:MM:SS',
  'YYYY.MM.DD',
  'YYYY.MM.D',
  'D.M.YYYY',
  'MM/DD/YY',
  'M/D/YY',
  'DD/MM/YY',
  'D/M/YY',
  'YYYY.MM.DD HH:MM:SS',
  'YYYY.MM.DD HH:MM',
  // 2. Time only
  'HH:MM',
  'HH:MM A',
  'HH:MM:SS A',
  'HH:MM:SS.SSS A',
  'HH:MM Z',
  'HH:MM:SS Z',
  'HH:MM:SS',
  'HH:MM:SS.SSS',
  // 3. Combined date-time
  'YYYY-MM-DDTHH:MM',
  'YYYY-MM-DDTHH:MMZ',
  'YYYY-MM-DDTHH:MM:SS',
  'YYYY-MM-DDTHH:MM:SS.SSS',
  'YYYY-MM-DD HH:MM:SS',
  'YYYY-MM-DD HH:MM:SS.SSS',
  'YYYY-MM-DD HH:MM',
  'MM/DD/YYYY HH:MM',
  'MM/D/YYYY HH:MM',
  'MM/DD/YYYY HH:MM A',
  'MM/D/YYYY HH:MM A',
  'MM/DD/YYYY HH:MM:SS',
  'MM/D/YYYY HH:MM:SS',
  'DD/MM/YYYY HH:MM',
  'D/MM/YYYY HH:MM',
  'DD/MM/YYYY HH:MM A',
  'D/MM/YYYY HH:MM A',
  'DD/MM/YYYY HH:MM:SS',
  'D/MM/YYYY HH:MM:SS',
  'DD/MM/YYYY HH:MM:SS A',
  'D/MM/YYYY HH:MM:SS A',
  'DD/MM/YYYY HH:MM:SS.SSS',
  'DD/MM/YYYY HH:MM:SS.SSS A',
  'DD-MM-YYYY HH:MM',
  'D-MM-YYYY HH:MM',
  'DD-MM-YYYY HH:MM:SS',
  'D-MM-YYYY HH:MM:SS',
  'MM-DD-YYYY HH:MM',
  'M-DD-YYYY HH:MM',
  'MM-D-YYYY HH:MM',
  'M-D-YYYY HH:MM',
  'MM-DD-YYYY HH:MM:SS',
  'M-DD-YYYY HH:MM:SS',
  'MM-D-YYYY HH:MM:SS',
  'M-D-YYYY HH:MM:SS',
  'MMM DD, YYYY HH:MM',
  'MMM D, YYYY HH:MM',
  'MMM DD, YYYY HH:MM:SS',
  'MMM D, YYYY HH:MM:SS',
  'MMM DD, YYYY HH:MM A',
  'MMM D, YYYY HH:MM A',
  'MMM DD, YYYY HH:MM:SS A',
  'MMM D, YYYY HH:MM:SS A',
  'MMM DD, YYYY HH:MM:SS.SSS',
  'MMM D, YYYY HH:MM:SS.SSS',
  'MMM DD, YYYY HH:MM:SS.SSS A',
  'MMM D, YYYY HH:MM:SS.SSS A',
  'YYYY-MM-DDTHH:MM:SSZ',
  'YYYY-MM-DDTHH:MM:SS.SSSZ',
  'YYYY-MM-DD HH:MM:SS Z',
] as const
