/**
 * Supported output format strings for date/time formatting.
 * Use with the optional `outputFormat` argument of `genRecurDateBasedList`.
 * Cannot be used together with `localeString` (lang or formatOptions).
 * Supports both YYYY/MM/DD and yyyy/mm/dd conventions; Z = timezone offset (e.g. +00:00).
 */
export const OUTPUT_FORMATS = [
    // --- Uppercase convention (YYYY, MM, DD, HH, etc.) ---
    // 1. Date only (DD = 2-digit day, D = day without leading zero)
    'MM/DD/YYYY',
    'MM/D/YYYY',
    'M/DD/YYYY',
    'M/D/YYYY',
    'DD/MM/YYYY',
    'D/MM/YYYY',
    'DD/M/YYYY',
    'D/M/YYYY',
    'YYYY-MM-DD',
    'YYYY-MM-D',
    'DD-MM-YYYY',
    'D-MM-YYYY',
    'YYYY/MM/DD',
    'YYYY/MM/D',
    'MMM DD, YYYY',
    'MMM D, YYYY',
    'MMMM DD, YYYY',
    'MMMM D, YYYY',
    'dddd, MMMM DD, YYYY',
    'dddd, MMMM D, YYYY',
    'DD MMM YYYY',
    'D MMM YYYY',
    'DD MMMM YYYY',
    'D MMMM YYYY',
    'ddd, DD MMM YYYY HH:mm:ss GMT',
    'ddd, D MMM YYYY HH:mm:ss GMT',
    'YY/MM/DD',
    'YY/MM/D',
    'YYYYDDD',
    'DD.MM.YYYY',
    'D.MM.YYYY',
    'DD.MM.YY',
    'D.MM.YY',
    'YYYY.MM.DD',
    'YYYY.MM.D',
    'D.M.YYYY',
    // 2. Time only
    'hh:mm',
    'hh:mm A',
    'hh:mm:ss',
    'hh:mm:ss A',
    'hh:mm:ss.SSS',
    'hh:mm:ss.SSS A',
    'HH:mm',
    'HH:mm:ss',
    'HH:mm:ss.SSS',
    // 3. Combined date-time
    'YYYY-MM-DDTHH:mm:ss',
    'YYYY-MM-DDTHH:mm:ss.SSS',
    'YYYY-MM-DD HH:mm:ss',
    'YYYY-MM-DD HH:mm:ss.SSS',
    'MM/DD/YYYY hh:mm',
    'MM/D/YYYY hh:mm',
    'MM/DD/YYYY hh:mm A',
    'MM/D/YYYY hh:mm A',
    'DD/MM/YYYY hh:mm',
    'D/MM/YYYY hh:mm',
    'DD/MM/YYYY hh:mm A',
    'D/MM/YYYY hh:mm A',
    'DD/MM/YYYY hh:mm:ss',
    'D/MM/YYYY hh:mm:ss',
    'DD/MM/YYYY hh:mm:ss A',
    'D/MM/YYYY hh:mm:ss A',
    'DD/MM/YYYY hh:mm:ss.SSS',
    'DD/MM/YYYY hh:mm:ss.SSS A',
    'MMM DD, YYYY hh:mm',
    'MMM D, YYYY hh:mm',
    'MMM DD, YYYY hh:mm A',
    'MMM D, YYYY hh:mm A',
    'MMM DD, YYYY hh:mm:ss',
    'MMM D, YYYY hh:mm:ss',
    'MMM DD, YYYY hh:mm:ss A',
    'MMM D, YYYY hh:mm:ss A',
    'MMM DD, YYYY hh:mm:ss.SSS',
    'MMM D, YYYY hh:mm:ss.SSS',
    'MMM DD, YYYY hh:mm:ss.SSS A',
    'MMM D, YYYY hh:mm:ss.SSS A',
    'YYYY-MM-DDTHH:mm:ssZ',
    'YYYY-MM-DDTHH:mm:ss.SSSZ',
    'YYYY-MM-DD HH:mm:ss Z',
    // --- Lowercase convention (yyyy, mm, dd) - original set ---
    'yyyy-mm-dd',
    'yyyy-mm-dd HH:mm:ss',
    'yyyy-mm-dd HH:mm:ss.SSS',
    'yyyy-mm-dd HH:mm:ss.SSS Z',
    'yyyy/mm/dd',
    'yyyy/mm/dd HH:mm:ss',
    'yyyy/mm/dd HH:mm:ss.SSS',
    'yyyy/mm/dd HH:mm:ss.SSS Z',
    'mm-dd-yyyy',
    'mm-dd-yyyy HH:mm:ss',
    'mm-dd-yyyy HH:mm:ss.SSS',
    'mm-dd-yyyy HH:mm:ss.SSS Z',
    'mm/dd/yyyy',
    'mm/dd/yyyy HH:mm:ss',
    'mm/dd/yyyy HH:mm:ss.SSS',
    'mm/dd/yyyy HH:mm:ss.SSS Z',
    'dd-mm-yyyy',
    'dd-mm-yyyy HH:mm:ss',
    'dd-mm-yyyy HH:mm:ss.SSS',
    'dd-mm-yyyy HH:mm:ss.SSS Z',
    'dd/mm/yyyy',
    'dd/mm/yyyy HH:mm:ss',
    'dd/mm/yyyy HH:mm:ss.SSS',
    'dd/mm/yyyy HH:mm:ss.SSS Z',
] as const

