/**
 * Supported output format strings for date/time formatting.
 * Use with the optional `outputFormat` argument of `genRecurDateBasedList`.
 * Can be used with `localeString.lang` for localized month/weekday names; cannot be combined with `localeString.formatOptions`.
 * All tokens are uppercase: YYYY, MM, DD, HH, SS, SSS, A (AM/PM), EEE/EEEE (weekday), MMM/MMMM, DDD (day of year), Z (timezone).
 */
export const OUTPUT_FORMATS = [
    // 1. Date only (DD = 2-digit day, D = day without leading zero)
    'MM/DD/YYYY',
    'MM/D/YYYY',
    'M/DD/YYYY',
    'M/D/YYYY',
    'DD/MM/YYYY',
    'D/MM/YYYY',
    'DD/M/YYYY',
    'D/M/YYYY',
    'YYYY-MM-DD',
    'YYYY-MM-D',
    'DD-MM-YYYY',
    'D-MM-YYYY',
    'YYYY/MM/DD',
    'YYYY/MM/D',
    'MMM DD, YYYY',
    'MMM D, YYYY',
    'MMMM DD, YYYY',
    'MMMM D, YYYY',
    'EEEE, MMMM DD, YYYY',
    'EEEE, MMMM D, YYYY',
    'EEEE, DD MMM YYYY',
    'EEEE, D MMM YYYY',
    'DD MMM YYYY',
    'D MMM YYYY',
    'DD MMMM YYYY',
    'D MMMM YYYY',
    'EEE, DD MMM YYYY HH:MM:SS GMT',
    'EEE, D MMM YYYY HH:MM:SS GMT',
    'YY/MM/DD',
    'YY/MM/D',
    'YY-MM-DD',
    'YY-MM-D',
    'YYYYMMDD',
    'YYYYDDD',
    'DD.MM.YYYY',
    'D.MM.YYYY',
    'DD.MM.YY',
    'D.MM.YY',
    'YYYY.MM.DD',
    'YYYY.MM.D',
    'D.M.YYYY',
    'MM/DD/YY',
    'M/D/YY',
    'DD/MM/YY',
    'D/M/YY',
    'YYYY.MM.DD HH:MM:SS',
    'YYYY.MM.DD HH:MM',
    // 2. Time only
    'HH:MM',
    'HH:MM A',
    'HH:MM:SS A',
    'HH:MM:SS.SSS A',
    'HH:MM Z',
    'HH:MM:SS Z',
    'HH:MM:SS',
    'HH:MM:SS.SSS',
    // 3. Combined date-time
    'YYYY-MM-DDTHH:MM',
    'YYYY-MM-DDTHH:MMZ',
    'YYYY-MM-DDTHH:MM:SS',
    'YYYY-MM-DDTHH:MM:SS.SSS',
    'YYYY-MM-DD HH:MM:SS',
    'YYYY-MM-DD HH:MM:SS.SSS',
    'MM/DD/YYYY HH:MM',
    'MM/D/YYYY HH:MM',
    'MM/DD/YYYY HH:MM A',
    'MM/D/YYYY HH:MM A',
    'DD/MM/YYYY HH:MM',
    'D/MM/YYYY HH:MM',
    'DD/MM/YYYY HH:MM A',
    'D/MM/YYYY HH:MM A',
    'DD/MM/YYYY HH:MM:SS',
    'D/MM/YYYY HH:MM:SS',
    'DD/MM/YYYY HH:MM:SS A',
    'D/MM/YYYY HH:MM:SS A',
    'DD/MM/YYYY HH:MM:SS.SSS',
    'DD/MM/YYYY HH:MM:SS.SSS A',
    'MMM DD, YYYY HH:MM',
    'MMM D, YYYY HH:MM',
    'MMM DD, YYYY HH:MM:SS',
    'MMM D, YYYY HH:MM:SS',
    'MMM DD, YYYY HH:MM A',
    'MMM D, YYYY HH:MM A',
    'MMM DD, YYYY HH:MM:SS A',
    'MMM D, YYYY HH:MM:SS A',
    'MMM DD, YYYY HH:MM:SS.SSS',
    'MMM D, YYYY HH:MM:SS.SSS',
    'MMM DD, YYYY HH:MM:SS.SSS A',
    'MMM D, YYYY HH:MM:SS.SSS A',
    'YYYY-MM-DDTHH:MM:SSZ',
    'YYYY-MM-DDTHH:MM:SS.SSSZ',
    'YYYY-MM-DD HH:MM:SS Z',
] as const
